<?php

namespace AppBundle\Repository;

/**
 * GrocItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrocItemRepository extends \Doctrine\ORM\EntityRepository
{
}
