<?php

namespace AppBundle\Repository;

/**
 * GrocListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrocListRepository extends \Doctrine\ORM\EntityRepository
{
}
