<?php

namespace WebGrocBundle\Repository;

/**
 * GrocTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrocTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
