<?php

namespace WebGrocBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrocListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrocListRepository extends EntityRepository {

    public function getCount() {
        $qb = $this->createQueryBuilder('l');

        $qb->select('COUNT(l)');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
