<?php

namespace WebGrocBundle\Repository;

use Doctrine\ORM\EntityRepository;
use WebGrocBundle\Entity\GrocList;

/**
 * GrocItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrocItemRepository extends EntityRepository {

    public function getCount() {
        $qb = $this->createQueryBuilder('i');

        $qb->select('COUNT(i)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function findNewForList(GrocList $list) {
        $qb = $this->createQueryBuilder('i');

        $qb->select('i');
        if ($list->getItems()->count() > 0) {
            $qb->where(
                $qb->expr()->notIn('i', ':items')
            );
            $qb->setParameter('items', $list->getItems());
        }

        return $qb->getQuery()->execute();
    }
}
